### ISSUE TITLE
Get current speed in meaningful unit

### ISSUE THREAD

**Issue by dogoepp** [resibots/libdynamixel#14]
Currently, we can only get the current speed as an integer. There should be something similar to get__current_position_angle to do the conversion to an other unit.

**Question:** Which is the unit we should use ? For information, Robotis's documentation gives rpm values.

**Comment by costashatz** [comment]
> Question: Which is the unit we should use ? For information, Robotis's documentation gives rpm values.

I think we should stick to `SI` units (rad/s).

**Comment by jbmouret** [comment]
An angle should be in radians.

-- JBM

**Comment by costashatz** [comment]
> An angle should be in radians.

We are talking about speed/velocity. So it should be `rad/s`.

**Comment by dogoepp** [comment]
fixed with #21.
