### ISSUE TITLE
Protocol 2 brought to MX series ?

### ISSUE THREAD

**Issue by dogoepp** [resibots/libdynamixel#30]
There is now a firmware for MX28, MX64 and MX106 that [talks protocol 2](http://emanual.robotis.com/#dynamixel-control-table).

Open questions:

1. how should we handle this in our library : the model numbers changed so it is straightforward
2. how to perform the upgrade, if possible : through R+
3. once upgraded, can they still talk protocol 1

**Comment by naoki-mizuno** [comment]
I'm currently trying to write a description hpp for MX106, mostly basing it off of `pro_h54_200_s500.hpp
`. However, I wasn't sure how to find the [non-common fields](https://github.com/resibots/libdynamixel/blob/f62232cad1c86d9573f1b63396fbbe9f45399231/src/dynamixel/servos/pro_h54_200_s500.hpp#L115-L133). Is there a list somewhere?

**Comment by dogoepp** [comment]
The common fields are declared in [`servo.hpp`](https://github.com/resibots/libdynamixel/blob/f62232cad1c86d9573f1b63396fbbe9f45399231/src/dynamixel/servos/servo.hpp#L113-L131). Don't forget either to add any new fields to [`base_serv.hpp`](https://github.com/resibots/libdynamixel/blob/f62232cad1c86d9573f1b63396fbbe9f45399231/src/dynamixel/servos/base_servo.hpp#L60-L122) which declares methods for all fields that belong to at least one supported model.

**Comment by dogoepp** [comment]
Also, we will need to update `auto_detect.hpp`.

**Comment by naoki-mizuno** [comment]
Thanks! I'll take a look at those files and see what I can do.

**Comment by naoki-mizuno** [comment]
I've implemented the header file for MX106 supporting protocol 2. I haven't tested this with on actual MX106 yet (I will as soon as I get access to one, which will be within the next week), but any feedback regarding naming convention/ordering etc. is welcome! The read/write fields, address, and the data size in bytes are based on the [official control table](http://support.robotis.com/en/product/actuator/dynamixel/mx_series/mx-106(2.0).htm).

https://github.com/naoki-mizuno/libdynamixel/commit/27e0f908ef4fb53183a10cf6882a343c0a79e369

**Comment by dogoepp** [comment]
It looks great! Let me know when you have had an occasion to test it.

Maybe you could put the new fields in `base_servo.hpp` in the group that best matches their meanings ?

**Comment by naoki-mizuno** [comment]
I tested it and it worked! :smile: I used an MX106 with protocol version 2 (firmware 41.0). `p2-dynamixel list` showed:

```
Connected devices (1) :
1       Mx106P2
```

I then used the `dynamixel_control_hw` to successfully do a position control on the MX106.

> Maybe you could put the new fields in base_servo.hpp in the group that best matches their meanings ?

I'm not quite sure what you mean. I couldn't find the grouping condition for the `BASE_FIELD`s in `base_servo.hpp` (for example, [these lines](https://github.com/resibots/libdynamixel/blob/33c06215988cb5a5f72616a7616e97b4f9857ed4/src/dynamixel/servos/base_servo.hpp#L106-L120) seems have been added because of the fields in Dynamixel Pro control table). If you can give a pointer on how to organize them, I'd be glad to incorporate that and send a PR!

**Comment by naoki-mizuno** [comment]
I've added support for MX-28 and MX-64 in addition to the already tested MX-106. I have tested MX-28, but I couldn't find an available MX-64. If you have access to one could you test it?

**Comment by dogoepp** [comment]
Maybe this is actually a good time to group the fields in a logical manner : separating the ROM and RAM fields and within these categories the ones specific to protocol2. I can do the changes and do a pull request on your branch, if you wish.

**Comment by naoki-mizuno** [comment]
Ah, that makes sense. If you could send me a PR that would be great. Or, maybe just merge #45 and make the changes on this repo's `master` branch :)

**Comment by dogoepp** [comment]
You're right. I'll do the changes directly on this repository.

Besides, I could not upgrade the firmware of one of our MX-64. I tried using RobotPlus 2.0 but it did not offer to upgrade the firmware. How did you do ?

**Comment by naoki-mizuno** [comment]
> You're right. I'll do the changes directly on this repository.

:+1:

> I tried using RobotPlus 2.0 but it did not offer to upgrade the firmware. How did you do ?

I had to upgrade the R+ Manager to the latest version. Otherwise, it didn't recognize the MX servos. Sometimes it doesn't automatically prompt you that a latest version is available, and you need to click on the "update" button (left column, second button from the right next to the power icon).

![R+ Manager](http://www.robotis.us/product_images/uploaded_images/manager-2-1.jpg)

**Comment by dogoepp** [comment]
Re-organisation of the fields is done in #47.

As for testing with MX-64, I could not succeed to upgrade the firmware. R+ manager says that I have the latest version of the firmware. I assume that it means that the 3-wire version of MX-64 cannot be upgraded. Which version of the MX servos do you have ?

**Comment by naoki-mizuno** [comment]
I tested using the newer MX series. I remember hearing something about the older ones not being able to update itself to the latest firmware. If I get access to a newer MX-64 I'll make sure to test the code on that. Anyways I think the issue can be closed now :)

**Comment by dogoepp** [comment]
Yes, thanks
