### ISSUE TITLE
Angle limit error message boundaries unit problem

### ISSUE THREAD

**Issue by elkhadiy** [resibots/libdynamixel#41]
```bash
$ ./dynamixel position --id 1 --angle 180
Servo: error while setting position (rad) in servo with ID 1: 
Minimum: 30, Maximum: 330, Given: 10313.2
```

plz switch the boundaries' unit from degres to gradiant, it's a little confusing even though it says (rad) and (in radians) in --help
30° -> ~0.524 rad
330° -> ~5.76 rad

**Comment by dogoepp** [comment]
Solved by #42
