### ISSUE TITLE
RX-64 support?

### ISSUE THREAD

**Issue by Rayman** [resibots/libdynamixel#49]
I'm trying to get this library to work with my dynamixel. Is the RX line supported? I could not find any implementation for it. `dynamixel list` returns nothing.

**Comment by dogoepp** [comment]
Hello @Rayman,
Indeed, we did not implement the RX control table. I can offer some help for you to make the one you needs. It's simple but just needs time to be done.

You need to create a new file named for instance `rx10.hpp` in the `src/dynamixel/servos` folder. The others file in this folder show you what needs to be there.

Then, you also need to include this new file from `src/dynamixel/servos/servos.hpp` and add two lines in the Protocol1 version of `get_servos()` in `src/dynamixel/auto_detect.hpp`.

The last addition is the one that will allow `dynamixel list` to recognise your actuators. Don't forget also to set the right port with `-p` and the right baudrate with `-b` if they are not the default values.

**Comment by jbmouret** [comment]
The reason we did not do it is that we have no RX dynamixels in the lab (only DX/AX/MX/Pro).

**Comment by Rayman** [comment]
Thanks for your reaction. I didn't have time to implement that, so I switched to the official c++ drivers: https://github.com/ROBOTIS-GIT/dynamixel-workbench
