### ISSUE TITLE
Comment out Send and Receive Print Statements

### ISSUE THREAD

**Issue by jlane1590** [resibots/libdynamixel#58]
Please add a DEBUG flag or comment out the Send and Receive print statements in the usb2dynamixel.hpp. The print statements used to be commented out but now they flood the terminal.

https://github.com/resibots/libdynamixel/blob/a62eee31e523413572488ce6cea9944a902c95f2/src/dynamixel/controllers/usb2dynamixel.hpp#L150

Thanks

**Comment by dogoepp** [comment]
While waiting for the official maintainers to validate the merge request, you can use the branch [fix-#58](https://github.com/resibots/libdynamixel/tree/fix-%2358)
